# Generated by Django 4.1.2 on 2022-10-12 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('amount', models.FloatField()),
                ('customer', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('status', models.CharField(blank=True, choices=[('Not Set', ''), ('confirm', 'confirm'), ('rejected', 'rejected'), ('Third Part', 'Third Part')], default='', max_length=20)),
                ('type', models.CharField(choices=[('cr', 'Credited'), ('dr', 'Debited')], max_length=10)),
                ('comment', models.TextField()),
            ],
        ),
    ]
