# Generated by Django 4.1.2 on 2022-10-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadstatement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
