# Generated by Django 4.1.2 on 2022-10-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadstatement', '0002_auditdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditdata',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='auditdata',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
