# Generated by Django 4.1.2 on 2022-10-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadstatement', '0003_alter_auditdata_amount_alter_auditdata_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('amount', models.FloatField(default=0)),
                ('name', models.CharField(default='', max_length=100)),
                ('bank_name', models.CharField(default='', max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(blank=True, choices=[('Not Set', ''), ('confirm', 'confirm'), ('rejected', 'rejected'), ('Third Part', 'Third Part')], default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('amount', models.FloatField(default=0)),
                ('name', models.CharField(default='', max_length=100)),
                ('bank_name', models.CharField(default='', max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(blank=True, choices=[('Not Set', ''), ('confirm', 'confirm'), ('rejected', 'rejected'), ('Third Part', 'Third Part')], default='', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='AuditData',
        ),
    ]
