# Generated by Django 4.1.2 on 2022-10-14 03:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadstatement', '0004_depositrequest_withdrawalrequest_delete_auditdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositrequest',
            name='audit_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='audit_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
