# Generated by Django 4.1.2 on 2022-10-14 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadstatement', '0005_depositrequest_audit_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositrequest',
            old_name='date',
            new_name='request_date',
        ),
        migrations.RenameField(
            model_name='withdrawalrequest',
            old_name='date',
            new_name='request_date',
        ),
    ]
