# Generated by Django 4.1.2 on 2022-10-15 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadstatement', '0006_rename_date_depositrequest_request_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='audit_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
