# Generated by Django 4.1.2 on 2022-10-19 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadstatement', '0007_bankstatement_audit_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositrequest',
            old_name='name',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='withdrawalrequest',
            old_name='name',
            new_name='customer',
        ),
    ]
