# Generated by Django 4.1.2 on 2022-10-19 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadstatement', '0008_rename_name_depositrequest_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositrequest',
            old_name='request_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='withdrawalrequest',
            old_name='request_date',
            new_name='date',
        ),
    ]
